# ============================================================================
# AFO Chat Application - Package Configuration
# ============================================================================
# Package configuration for the AFO (Afaan Oromoo Chat Services) application.
# This Flutter app provides comprehensive chat functionality with voice/video
# calling capabilities, admin dashboard, and notification system for the
# Afaan Oromoo speaking community.
# ============================================================================

name: afochatapplication
description: AFO (Afaan Oromoo Chat Services) - Flutter chat app with voice/video calling, admin dashboard, and notifications
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # Networking & HTTP
  http: ^1.2.2
  dio: ^5.4.0
  
  # Authentication & Security
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Firebase Services (for notifications and backend)
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  
  # Local Notifications
  flutter_local_notifications: ^19.4.2
  
  # UI & Charts
  fl_chart: ^0.71.0
  
  # Utilities
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.20.2
  uuid: ^4.5.1
  
  # Media handling dependencies
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  video_player: ^2.9.1
  audioplayers: ^6.1.0
  image: ^4.2.0
  video_thumbnail: ^0.5.3
  
  # Permissions
  permission_handler: ^12.0.1
  
  # WebRTC for video calling
  flutter_webrtc: ^1.2.0
  
  # Additional UI components
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  shared_preferences: any
  vibration: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/google_logo.png
  
  # Fonts configuration
  # NOTE: Fonts are currently not present in the repository under the `fonts/` directory.
  # The font entries have been temporarily commented out to avoid asset not found
  # errors during builds. Re-add these entries after placing the font files in
  # the `fonts/` directory with exact filenames.
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: OromiOromoo
  #     fonts:
  #       - asset: fonts/OromiOromoo-Regular.ttf
  #       - asset: fonts/OromiOromoo-Bold.ttf
  #         weight: 700

# Platform-specific configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/afo_logo.png"
  min_sdk_android: 21

# Additional metadata
metadata:
  project_type: "flutter_app"
  features:
    - "chat_messaging"
    - "voice_video_calls" 
    - "admin_dashboard"
    - "notifications"
    - "user_management"
    - "content_moderation"